# Generated by Django 3.2.6 on 2021-09-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
