# Generated by Django 3.2.6 on 2021-09-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='flags',
        ),
        migrations.AddField(
            model_name='score',
            name='flags',
            field=models.ManyToManyField(related_name='user_flags', to='scoring.Flags'),
        ),
    ]
